version: "3.9"
 
services: 
  db: 
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    image: seven_easy
    container_name: seven_easy 
    depends_on:
      - db
    ports:
      - "4000:4000"
    env_file:
      - .env
    restart: always

volumes:
  postgres_data:
